package org.sapzil.eaglejump.example

import org.reactivestreams.Publisher
import org.sapzil.eaglejump.example.protocol.DocumentDTO
import org.sapzil.eaglejump.example.protocol.GetDocumentRequest

// This should be generated by compiler later
interface DocumentService {
    interface BlockingClient {
        fun getDocument(request: GetDocumentRequest): DocumentDTO
    }

    interface GetDocument {
        fun invoke(request: GetDocumentRequest): Publisher<DocumentDTO>
    }
}